#!/usr/bin/env node

/**
 * AuthScape Post-Install Script
 * Automatically sets up sitemap.xml for Next.js projects (both Pages Router and App Router)
 */

const fs = require('fs');
const path = require('path');

// Template for Pages Router
const PAGES_ROUTER_TEMPLATE = `// Auto-generated by AuthScape - Do not edit manually
import { generateSitemap } from 'authscape/src/services/sitemapService';

export async function getServerSideProps({ req, res }) {
  const apiBaseUri = process.env.apiUri;

  if (!apiBaseUri) {
    console.error('AuthScape Sitemap Error: apiUri is not configured. Please set process.env.apiUri in your .env.local file or environment variables.');
    res.statusCode = 500;
    res.setHeader('Content-Type', 'text/plain');
    res.write('Sitemap configuration error: API URI not set. Please configure process.env.apiUri in your environment variables.');
    res.end();
    return { props: {} };
  }

  await generateSitemap(req, res, apiBaseUri);

  return { props: {} };
}

export default function Sitemap() {
  return null;
}
`;

// Template for App Router
const APP_ROUTER_TEMPLATE = `// Auto-generated by AuthScape - Do not edit manually
import { createSitemapRoute } from 'authscape/src/lib/sitemap-route';

export const GET = createSitemapRoute(process.env.apiUri);
`;

// ---------------------------------------------------------------------------
// /signin-oidc page templates
// ---------------------------------------------------------------------------
// AuthScapeApp reads the PKCE `code` query param from `useSearchParams()`
// (next/navigation). If the consumer doesn't have a `/signin-oidc` page, the
// IDP's redirect back lands on Next.js's 404 page — and Webkit/Safari
// doesn't reliably hydrate `useSearchParams()` on the 404 page. The code is
// never read, the user is stuck.
//
// Making /signin-oidc a real Next.js page (200 status) fixes this in every
// browser. The page itself is a placeholder; AuthScapeApp's signInValidator
// does the actual token exchange.

const SIGNIN_OIDC_PAGES_ROUTER_TEMPLATE = `// Auto-generated by AuthScape - Do not edit manually.
// Exists so /signin-oidc returns HTTP 200 (not the Next.js 404 page).
// Required for Webkit/Safari: useSearchParams() doesn't hydrate on the 404
// page in Webkit, so the PKCE 'code' query param is never read and sign-in
// silently stalls. With this real page in place, AuthScapeApp's
// signInValidator picks up the code and completes the exchange normally.
export default function SignInOidc() {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "60vh",
        fontFamily: "system-ui, -apple-system, Segoe UI, sans-serif",
        color: "#666",
      }}
    >
      Signing you in…
    </div>
  );
}
`;

const SIGNIN_OIDC_APP_ROUTER_TEMPLATE = `// Auto-generated by AuthScape - Do not edit manually.
// Exists so /signin-oidc returns HTTP 200 (not the Next.js 404 page).
// Required for Webkit/Safari to pick up the PKCE 'code' query param.
export default function SignInOidc() {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "60vh",
        fontFamily: "system-ui, -apple-system, Segoe UI, sans-serif",
        color: "#666",
      }}
    >
      Signing you in…
    </div>
  );
}
`;

function detectProjectStructure() {
  // Get the parent directory where the user ran npm install
  // This goes up from node_modules/authscape to the project root
  const projectRoot = path.resolve(process.cwd(), '../..');

  // Check for App Router (prioritize newer approach)
  const appDirs = [
    path.join(projectRoot, 'app'),
    path.join(projectRoot, 'src', 'app'),
  ];

  for (const dir of appDirs) {
    if (fs.existsSync(dir)) {
      return {
        type: 'app',
        baseDir: dir,
        sitemapPath: path.join(dir, 'sitemap.xml'),
        filePath: path.join(dir, 'sitemap.xml', 'route.js'),
      };
    }
  }

  // Check for Pages Router
  const pagesDirs = [
    path.join(projectRoot, 'pages'),
    path.join(projectRoot, 'src', 'pages'),
  ];

  for (const dir of pagesDirs) {
    if (fs.existsSync(dir)) {
      return {
        type: 'pages',
        baseDir: dir,
        sitemapPath: path.join(dir, 'sitemap.xml.js'),
        filePath: path.join(dir, 'sitemap.xml.js'),
      };
    }
  }

  return null;
}

function setupSitemap() {
  const structure = detectProjectStructure();

  if (!structure) {
    console.log('⚠️  Next.js pages/app directory not found. Skipping sitemap setup.');
    console.log('   To set up manually, visit: https://authscape.com/docs/sitemap');
    return;
  }

  // Check if sitemap file already exists
  if (fs.existsSync(structure.filePath)) {
    // File exists, don't overwrite
    return;
  }

  try {
    if (structure.type === 'app') {
      // App Router: Create directory first, then route.js inside it
      if (!fs.existsSync(structure.sitemapPath)) {
        fs.mkdirSync(structure.sitemapPath, { recursive: true });
      }
      fs.writeFileSync(structure.filePath, APP_ROUTER_TEMPLATE, 'utf8');
      console.log('✅ AuthScape sitemap configured at /sitemap.xml (App Router)');
    } else {
      // Pages Router: Just create the file
      fs.writeFileSync(structure.filePath, PAGES_ROUTER_TEMPLATE, 'utf8');
      console.log('✅ AuthScape sitemap configured at /sitemap.xml (Pages Router)');
    }
  } catch (error) {
    // Silent failure - don't break the install
    console.log('⚠️  Could not auto-configure sitemap:', error.message);
    console.log('   To set up manually, visit: https://authscape.com/docs/sitemap');
  }
}

function setupSigninOidc() {
  const structure = detectProjectStructure();
  if (!structure) return;

  const targetFile =
    structure.type === 'app'
      ? path.join(structure.baseDir, 'signin-oidc', 'page.js')
      : path.join(structure.baseDir, 'signin-oidc.js');

  if (fs.existsSync(targetFile)) {
    // File exists, don't overwrite — consumer may have their own handler
    return;
  }

  try {
    fs.mkdirSync(path.dirname(targetFile), { recursive: true });
    fs.writeFileSync(
      targetFile,
      structure.type === 'app' ? SIGNIN_OIDC_APP_ROUTER_TEMPLATE : SIGNIN_OIDC_PAGES_ROUTER_TEMPLATE,
      'utf8'
    );
    console.log(
      '✅ AuthScape signin-oidc page configured at /signin-oidc (' +
        (structure.type === 'app' ? 'App Router' : 'Pages Router') +
        ')'
    );
  } catch (error) {
    console.log('⚠️  Could not auto-configure /signin-oidc:', error.message);
    console.log('   Without this page, Safari users will fail to sign in.');
  }
}

// Run the setup
try {
  setupSitemap();
  setupSigninOidc();
} catch (error) {
  // Completely silent failure to avoid breaking npm install
  // Only log if there's an unexpected error
  if (process.env.DEBUG) {
    console.error('AuthScape postinstall error:', error);
  }
}
